### ISSUE TITLE
Request - Support applying background to dark theme (Gnome 42)

### ISSUE THREAD

**Issue by rventers** [naueramant/simon-stalenhag-wallpaper#4]
Script: [stalenhag.py line 206](https://github.com/naueramant/simon-stalenhag-wallpaper/blob/master/stalenhag.py#L206)

Currently, stalenhag.py applies the background to the light theme and not the dark theme. Looks like the `picture-uri` key only applies to the light theme whereas the `picture-uri-dark` key applies to the dark theme.

Source: https://github.com/GNOME/gsettings-desktop-schemas/blob/master/schemas/org.gnome.desktop.background.gschema.xml.in

This request is to support applying the background to the dark theme.

Possible update to the set_background method:
* Apply the background to both themes, or
* Determine current theme and apply the background to the appropriate theme.

Not sure which of those approaches would be the best option.

**Comment by naueramant** [comment]
Applying to both would be an okay solution in my opinion :) 

What do you think @rventers ? and if so will you make a PR?

**Comment by rventers** [comment]
Sure, sounds good!
https://github.com/naueramant/simon-stalenhag-wallpaper/pull/5
